# .render.yaml
# Single background worker only
services:
  - type: worker
    name: spx-data-fetcher-worker
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python workers/main.py"
    envVars:
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: TRADIER_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: OPTION_CHAINS_TABLE_ID
        sync: false
      - key: INDEX_PRICE_TABLE_ID
        sync: false